### ISSUE TITLE
Extension Upgrade Failed - DB Error - No Such Field

### ISSUE THREAD

**Issue by madelynnk** [progressivetech/net.ourpowerbase.sumfields#75]
I'm attempting to upgrade the extension from version 3.1.1 to 4.0.2 and get the error above. I've included more info below:

DB.php(976): PEAR_Error->PEAR_Error("DB Error: no such field", -19, 16, (Array:2), "CREATE TRIGGER civicrm_line_item_after_insert after insert ON civicrm_line_item... 

I also see this error: DB_common->raiseError(-19, NULL, NULL, NULL, "1054 ** Unknown column 'contact_id' in 'NEW'") 

I'm in Drupal 7, Civicrm 4.6.27, but I've tried after upgrading Civi to 5 and receive the same error. If I try to run the db updates, they hang up. I've been able to upgrade to later versions of 3 (3.1.2, 3.1.3).

Any suggestions?

**Comment by jmcclelland** [comment]
Hi @madelynnk  - The sumfields extension doesn't hold any data (it's all calculated from other data) - with the only exception of your configuration choices. So, I would suggest:

1. take a screen shot of your summary fields configuration screen
2. disable the extension
3. uninstall the extension
4. look in your custom fields - if you see any custom data groups called summary fields, delete all fields and delete the group itself

Then, install the new version and re-configure. 

Sorry, I know this is a bit janky, but sometimes civicrm and sumfields have a difficult time cleaning up after itself.

**Comment by madelynnk** [comment]
I've tried disabling and uninstalling the extension several times. I made sure that the summary fields custom data group was deleted. I even tried deleting civicrm_temp tables that had summary fields data from the DB. I then tried installing the new version and when I try and run the updates, receive these errors: 

1. Regenerating data hangs up. I try again and then skip past. DB updates complete
2. Error: Your configuration may be corrupted. Please disable and reenable this extension. Once I do that then,
3. Error: error deleting...
4. Once reenabled, another error: Failed to create custom fields & tables. Maybe they already exists?

I am then unable to trigger the summary fields and the summary fields custom data group has no fields.
Once I do this I then cannot search on any records receiving a "sorry I cannot perform that at this time DB error"

I guess something is corrupted, but I haven't a clue as to what, so I'll just stick with version 3.13. 
I appreciate your help, though.
