### ISSUE TITLE
After a migration and upgrade to 5.1 (using Drupal 7) I can no longer save summary fields settings

### ISSUE THREAD

**Issue by eidoander** [progressivetech/net.ourpowerbase.sumfields#42]
We migrated and then upgraded to 5.1 (Drupal 7, PHP 7.1). We first noticed a problem when we couldn't merge contacts. Got "No such field" errors. Checking the backtrace we traced it to summary fields. We looked at the admin and discovered that none of our settings were preserved. Tried to select and save them. The civicrm system message says successfully saved, changes will happen on cron job. However, the selections are not saved. Nothing happens.

Also, it is only the field selections that won't save. Financial Types, Event Types, etc. will save. Only the select boxes fail, not the dropdowns.

Any help or insight would be appreciated!

BTW: We have uninstalled and reinstalled summary fields and still unable to save field settings.

**Comment by jmcclelland** [comment]
It sounds like your summary fields custom fields are out of sync. Can you try:
 * Disable summary fields
 * Uninstall summary fields
 * Go to your Custom Data section and if you see a summary fields group of custom fields, delete them all

Then, try re-installing and see if it works better.

**Comment by eidoander** [comment]
Yes, will try. We have already tried uninstalling. Will now try uninstalling and deleting any custom data related to summary fields.


BTW: we have many custom letter templates that reference summary fields with tokens. Wonder if that could cause problems?


John Richardson
Director of Development
313.531.0111


[http://lcministries.org/wp-content/uploads/2012/06/logoHoriz_200x58.jpg]<http://lcministries.org>


<http://lcministries.org>

<http://lcministries.org>lcministries.org | lcm.life<http://lcministries.org>


[Facebook]<https://www.facebook.com/lcsemi> [Twitter] <http://twitter.com/lifechallengeLC>  [YouTube] <https://YouTube.com/user/Lifechallengesemi>



________________________________

**Comment by jmcclelland** [comment]
The existing tokens in templates should not cause the problem you are experiencing but... you will need to re-create the tokens after you finish this process because the tokens will have changed.

**Comment by eidoander** [comment]
Okay. Thanks, Jamie! Will try as you suggest then recreate the tokens...

**Comment by ericbarkham** [comment]
Following Jamie's suggestions, I first disabled the Summary Fields Extension. Next, I then uninstalled the extension. I checked the Custom Data and Screens menu under Administer to confirm the Summary Fields Extension did not show in the drop down menu. It was gone.
I then went to the Custom Data and Screens menu (which has been renamed by us to Special - LC Ministries}' I went to the Summary Fields Set and found 25 fields "enabled" When I began to delete these fields one at a time, I received this error message in each case.
"Error
DB Constraint Violation - custom_group_id should possibly be marked as mandatory for CustomField,create API. If so, please raise a bug report."
When I went back to the "more" tab in each field I found the same three choices showing (Disable, Move and Delete). I then decided to attempt to "Disable" these fields instead of "Deleting" them. The error message at this action indicated that because the field was "view" only it would not open an "edit" page. However, when I went back to that field and selected the "more" tab it now had the three options marked as "Enable, Move and Delete". When I looked at the list of fields I found that this was now "greyed" out. I did this with several fields and each became "greyed" out with the "Enable" option offered.
Last, I went back to these "disabled" fields and attempted to "Delete" each. The result was simply a continuously rotating CiviCRM Triangle logo which I allowed to run for over one-half hour without any results. If there are further suggestions, I will be happy to try them. Thanks for your help!

**Comment by jmcclelland** [comment]
Can you create a new custom data group and a new custom field and then delete those?

That should help narrow the problem - which is either a general problem creating and deleting custom data fields OR it is a specific problem with the summary fields custom data set.

**Comment by ericbarkham** [comment]
I created a new Custom Field Set (Test Custom Field Set) and added 5 fields to it. The five fields I created used a variety of types including plain text, Radio (Yes/No), Date, Money and a Checkbox. I checked a variety of records to make sure this new set appeared. (It did.) I then chose a record and filled in the five fields to make sure it was working. Again, success.
I returned to the fields in the set and deleted each of the five successfully.When I returned to the test contact record the "Test Custom Field Set" was gone although the set remained in the Custom Data set list. I then deleted the "Test Custom Field Set" with no difficulty.
Any suggestions as to the next possible step?

**Comment by jmcclelland** [comment]
Great, it sounds like whatever is going wrong, it's limited to the summary fields custom data group.

Do you have access to phpmyAdmin? In other words, a way to directly access the database tables and rows? 

If so, you may need to manually delete the summary field table and fields. Be sure to make a complete backup of your database before you begin.

You should see a table called civicrm_custom_group, which will have one record for the summary fields. This record will include a field called table_name. The value of that field is the name of the table you should drop. It will have a name like: civicrm_value_summary_fields_51. It may already be gone, but if it's not drop it.

Then, look for the table civicrm_custom_field. Here you will have to located all the rows with a field from the summary table, They should all have the same custom_group_id value (but that value may be missing). You should delete these individual rows in the table.

Lastly, delete the row in the civicrm_custom_group table that you started with - the one row with the summary fields group in it.

Now all traces of summary fields should be gone and you can install from scratch.

**Comment by ericbarkham** [comment]
Touchdown! Your precise step-by-step instructions walked us through to a successful conclusion. Sum Fields are up and running. My extreme thanks. Thank you for hanging in there with us.

**Comment by jmcclelland** [comment]
Excellent - thanks for much for reporting back (and providing such detailed error reports).

**Comment by ericbarkham** [comment]
By the way, your "Sum Fields" extension is a hallmark of our "Thank You" program! Couldn't do without it !
Blessings!
